server:
  port: 8081

spring:
  application:
    name: 'peixe-classe'
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka