server:
  port: 8080

spring:
  datasource: 
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/aquario
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: 'peixe-cloud'

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka